const icebreakers = [
  "Which celebrity was your childhood crush?",
  "What's something from your childhood that you still love today?",
  "What was your favorite cartoon as a kid?",
  "What's something that always gives you child-like joy?",
  "What was the first way you made money?",
  "What were your favorite games as a kid?",
  "What clubs were you a member of in school?",
  "What was your favorite subject in school?",
  "What was your least favorite subject in school?",
  "What sports did you play as a kid?",
  "What's one thing you are unbeatable at?",
  "What languages do you know how to speak?",
  "At trivia night, what category would you know most about?",
  "If you had to give a lecture on one thing, what would it be?",
  "What's an unusual skill you'd love to master?",
  "What's a side project you're working on or want to work on?",
  "What's the worst job you ever had?",
  "What's your dream job?",
  "What's the best perk you've ever enjoyed at a job?",
  "What would you like to do when you retire?",
  "What's your favorite thing about your job?",
  "What's your favorite holiday?",
  "What's your favorite holiday tradition?",
  "Do you play any sports?",
  "Have you ever done any extreme sports like skydiving or bungee jumping? If not, would you?",
  "What's something you've wanted to do but haven't done yet?",
  "Have you ever met anyone famous?",
  "What's your all-time favorite game?",
  "Are you a fan of video games, board games, or both?",
  "What recent game have you played that you would highly recommend to others?",
  "If you could live in any video game world, which one would you choose?",
  "Is there a specific game that holds nostalgic value for you?",
  "Do you enjoy cooperative or competitive games more?",
  "Are there any video game soundtracks that you enjoy?",
  "What's your favorite board game to play with friends or family?",
  "Have you ever created your own game, either a video game or a board game?",
  "Are there any games that you believe everyone should play at least once?",
  "Are there any game genres that you tend to gravitate towards?",
  "What's the most useful item you've purchased this year?",
  "What's your favorite self-care activity?",
  "Have you been pleasantly surprised by anything recently?",
  "What seemingly inconsequential thing could you not live without?",
  "What's the most useful thing you own?",
  "What has improved your quality of life so much that you wish you had done it sooner?",
  "What's a piece of advice that has stuck with you?",
  "What are you most excited about this year?",
  "What's something you love that people wouldn't expect?",
  "Do you collect anything?",
  "Do you care about your astrological sign?",
  "What was the worst injury you ever had?",
  "What are your biggest phobias?",
  "What simple thing still blows your mind?",
  "What's something new or interesting you've learned recently?",
  "What's your favorite quote?",
  "What's your favorite podcast?",
  "If someone gave you a gift card to any store, what place would you want it to be?",
  "What's your go-to amusement park ride?",
  "What's the best phrase or piece of slang people in your hometown use?",
  "What's a word or phrase in another language (or your own) that you like?",
  "What's a common word or phrase that you don't like?",
  "Which question can you ask to find out the most about a person?",
  "What's one thing many people hate but you love?",
  "What's something that's considered acceptable now but won't be in 100 years?",
  "What's an adult problem nobody prepared you for?",
  "What's a current trend that you don't understand?",
  "Do you have a 'bucket list'? What are some of the items on it?",
  "What's your best scar story?",
  "Describe a time you laughed so hard you cried.",
  "Have you ever experienced a natural disaster like a hurricane or tornado?",
  "Have you ever won a contest?",
  "Who was your most unique pet?",
  "If you could have any animal for a pet, what would it be?",
  "What's your favorite and least favorite holiday song?",
  "What album has no bad songs?",
  "Which song or album evokes a sense of nostalgia for you?",
  "What's your favorite song to sing?",
  "Which musician, alive or dead, do you wish you could see perform?",
  "What's the most memorable live music or theater event you've been to?",
  "What musical instrument would you play in a band?",
  "If you were forced to sing karaoke, what song would you pick?",
  "What song or album could you listen to on repeat?",
  "What song or album have you been listening to recently?",
  "What was the first concert you ever attended?",
  "What was the best concert you ever attended?",
  "Who is the most underappreciated artist or band that more people should listen to?",
  "Have you ever been to a music festival? If not, which one would you attend?",
  "What song makes you dance or sing along whenever you hear it?",
  "What's your guilty pleasure song or artist that you enjoy despite not being critically acclaimed?",
  "What was your favorite band ten years ago?",
  "What artist are you most excited to see new music from?",
  "What's your favorite movie?",
  "What movie or TV show can you rewatch over and over again?",
  "What was your favorite movie as a child?",
  "What movie do you recommend to others the most?",
  "What obscure or underrated movie should everyone watch?",
  "What's a popular movie that you cannot stand?",
  "What's the most recent movie you've seen? Would you recommend it?",
  "If you could step into the world of any movie, which one would you live in?",
  "If you could only watch three movies for the rest of your life, what would they be?",
  "What's the best holiday movie of all time?",
  "What's the best Halloween movie of all time?",
  "What's your favorite animated movie?",
  "What's the funniest movie you've ever seen?",
  "What's the best action movie of all time?",
  "What's the best horror movie of all time?",
  "Would you rather go to the movie theater or watch a movie from home?",
  "Have you had a part or been an extra in a movie?",
  "What movie do you wish you could watch again for the first time?",
  "What's your favorite movie genre to watch?",
  "What movie defined your generation?",
  "What's your favorite movie quote?",
  "What movie has the best cinematography?",
  "Have you ever been surprised by a plot twist in a movie?",
  "What's the most emotional or thought-provoking movie you've ever watched?",
  "Have you ever attended a movie premiere or film festival? If not, which one would you choose?",
  "What movie has the best soundtrack or score?",
  "What movie didn't live up to the hype?",
  "What movie sequels were better than the original?",
  "What's your guilty pleasure movie?",
  "What's the most visually stunning movie you've ever seen?",
  "Which movies are better than their books?",
  "What's the best romantic comedy?",
  "What movie has the best villain?",
  "Who is the most interesting Disney or Pixar character?",
  "What's a good 'the bad guy wins' movie?",
  "What's the best fight scene in a movie or show?",
  "What's the best couple in sitcom history?",
  "What's the single best episode of television you’ve ever seen?",
  "What movie has the best opening scene?",
  "What's a movie you will never watch again?",
  "What movie or show do you quote the most?",
  "What's your favorite current TV show?",
  "What's your all-time favorite TV show?",
  "What's your guilty pleasure TV show?",
  "What obscure or underrated TV show should everyone watch?",
  "What TV show do you recommend to others the most?",
  "What was your favorite TV show as a child?",
  "What's the worst TV show ever made?",
  "If you could live in any TV show, what would it be?",
  "Are you currently binge-watching any TV shows?",
  "What's the most binge-able show you've ever watched?",
  "What TV show has the best ensemble cast?",
  "What TV show were you initially skeptical about but ended up loving?",
  "What canceled TV show would you bring back for another season or a revival?",
  "What TV show have you watched multiple times from start to finish?",
  "Do you prefer binge-watching or watching TV shows weekly?",
  "What's your favorite TV show genre?",
  "What upcoming TV show are you excited to watch?",
  "Have you ever attended a TV show premiere or live taping? If not, which show would you choose?",
  "What TV show had the most disappointing ending?",
  "What TV show has the best theme song or opening credits sequence?",
  "What TV show has the best villain?",
  "What's your favorite reality TV show?",
  "What reality show would you want to be on?",
  "Have you ever been in a movie, TV show, or play? What was your role?",
  "What was your favorite book as a child?",
  "What's your all-time favorite book?",
  "What's the earliest book you remember?",
  "Are there any books that have influenced your perspective on life?",
  "If you could be a character from any book, who would you be?",
  "What fictional world from a book would you live in?",
  "What was the last book you read that you enjoyed?",
  "What's the last book you quit reading?",
  "If you could write a book, what genre would it be?",
  "What book have you read recently you would recommend?",
  "Do you prefer ebooks or physical books?",
  "Is there a book that you've read multiple times? If so, what draws you back to it?",
  "Do you prefer fiction or non-fiction books?",
  "What lesser-known book did you love?",
  "Who is your favorite author?",
  "What are you reading right now?",
  "What's your favorite ice cream flavor and ice cream topping?",
  "What's your favorite restaurant?",
  "What's your favorite dessert?",
  "What's your favorite type of cuisine?",
  "What's your favorite breakfast food?",
  "What's the best meal you've had recently?",
  "What's the best meal you've ever had?",
  "What's your caffeinated beverage of choice?",
  "What's the best Halloween candy?",
  "What's the best Easter candy?",
  "What's the most unusual food you've eaten? Would you eat it again?",
  "Are you a fan of spicy food? What's the hottest dish you've ever tried?",
  "What's the strangest food combination you've ever tried that turned out to be delicious?",
  "What's your go-to comfort food?",
  "You can eliminate one food from the earth. What's it?",
  "What was your least favorite food as a child? Do you still dislike it?",
  "What was your favorite food as a child? Do you still like it?",
  "If you could visit any country solely for its food, which one would you choose?",
  "If you could only eat one type of cuisine for the rest of your life, which would you choose?",
  "Have you ever taken a cooking or baking class? What did you learn?",
  "What foods have you always wanted to try but haven't had the opportunity to do so?",
  "What's the oddest or most unique food-related fact or trivia that you know?",
  "What's your go-to drink?",
  "What healthy food tastes just as good to you as unhealthy food?",
  "What's your culture's most underrated food?",
  "What food reminds you of childhood?",
  "Sweet or savory?",
  "What would one of the loading screen tips be if grocery shopping was a game?",
  "Do you fold your pizza?",
  "What toppings do you put on your pizza?",
  "What sauce, condiment, or dressing couldn't you live without?",
  "What food are you craving right now?",
  "What's the best kitchen gadget?",
  "What food trend annoys you?",
  "What's your favorite meal to cook?",
  "What's the most overrated food?",
  "What's a food that you are not willing to try?",
  "Are you a traveler or a homebody?",
  "Do you prefer traveling solo, with a partner, or in a group?",
  "What was your most recent trip within your county?",
  "What's the most memorable trip you've ever been on?",
  "What was your most recent trip outside of your country?",
  "What's your favorite place of all the places you've traveled?",
  "What's something you like to do when you travel to a new country?",
  "When was the last time you went somewhere for the first time?",
  "What's the most breathtaking natural scenery you've encountered during your travels?",
  "Have you experienced any travel mishaps or unexpected challenges during a trip?",
  "What travel destinations exceeded your expectations?",
  "Do you collect souvenirs when you travel? What's your favorite souvenir?",
  "Are there any travel destinations that you'd love to revisit?",
  "Have you ever traveled to attend a specific event or festival?",
  "What's the most adventurous activity you've ever done while traveling?",
  "Are there any landmarks or famous sites you've always wanted to visit?",
  "Have you ever been to a destination that felt like a hidden gem or off the beaten path?",
  "Are there any travel-related books, movies, or documentaries that have inspired you to explore new places?",
  "What's the next destination on your travel bucket list, and what interests you about it?",
  "If you could live anywhere in the world for a year, where would it be?",
  "If I visited your hometown, what local spots should I see? What should I avoid?",
  "Would you rather travel by car, train, or plane?",
  "Have you ever been to Disney Land or Disney World?",
  "If you could teleport anywhere in the universe right now, where would you go?",
  "Do you have a regular vacation spot?",
  "What's the most obscure superpower you would want?",
  "What superpower would you give to your arch-enemy?",
  "Who's your favorite superhero?",
  "What mischievous act would you carry out as an evil villain on your first day of work?",
  "If aliens landed on Earth and offered to take you with them, would you go?",
  "There is a free, round-trip shuttle to Mars. It will take one year to go, visit, and come back. Are you in?",
  "If you could travel to any other planet (real or fictional), where would you go?",
  "Would you rather travel to space or travel in time?",
  "If you had a time machine, would you go back in time or into the future?",
  "Would you rather have the ability to see 10 minutes into the future or 150 years into the future?",
  "Which fictional character or real person would you want by your side during a zombie apocalypse?",
  "Would you rather be in a zombie apocalypse or a robot apocalypse?",
  "If you had a magic button on your desk to bring you whatever you wanted, what would it summon?",
  "If you could have an unlimited supply of one thing for the rest of your life, what would you pick?",
  "If you could pick up a new skill in an instant what would it be?",
  "If you could magically become fluent in any language, what would it be?",
  "You've died, but instead of entering the afterlife, you've entered Earth 2.0. What makes Earth 2.0 better?",
  "What age do you wish you could be permanently?",
  "You are stranded on a remote desert island. Are you alone or with your worst enemy?",
  "What crime would you commit if you knew you would get away with it?",
  "If you could change places with anyone in the world, who would it be?",
  "What features would your dream house contain?",
  "What sport would you compete in if you were in the Olympics?",
  "If you could eliminate one thing from your daily routine, what would it be?",
  "If you could bring back any fashion trend what would it be?",
  "How would you spend your days if you had unlimited time and resources?",
  "What would you do if you had a fully paid year-long break from work?",
  "If you could be famous for one thing, what would it be?",
  "If you did not have to sleep, how would you spend the extra eight hours?",
  "If you could know the total truth to one question, what question would you ask?",
  "If you were an action figure, what two accessories would you come with?",
  "What question would you ask a psychic?",
  "If people came with a warning tag, what would yours be?",
  "If you could create your own world, what would it be like?",
  "If you could design a theme park, what would be the main attractions?",
  "What tasks would you assign to your personal robot assistant and what name would you give it?",
  "If you could have a magical wardrobe that leads to a different world, where would it take you?",
  "What dish would you ask your chef, who can cook any dish in the world, to prepare for you?",
  "If you could revive any extinct species, which one would you choose?",
  "Which dream would you interpret first if you could interpret dreams?",
  "Which historical artifact would you restore and what mysteries would it unveil if you could bring it back to its original condition?",
  "If you won the lottery what would you buy first?",
  "What minor annoyance would you wish on your worst enemy, every day, forever?",
  "What's something you remember that younger people wouldn't understand?",
  "What's something that was normal 20 years ago that isn't normal now?",
  "What's the best mental health advice you have?",
  "What are your best jury duty stories?",
  "What's just not the 'flex' that people think it is?",
  "What animal would you consider to be the cutest?",
  "What discontinued item/thing do you want to be brought back?",
  "What's something that you learned in school but got debunked as you got older?",
  "What's something that seems increasingly unappealing the older you get?",
  "What’s something you’ve tried that you’ll never, ever try again?",
  "What fictional object do you most want to own?",
];
